yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),

]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main'),
    path('group/<slug:slug>/', views.group_post, name='blog'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Жанр'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date', )

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    text = models.TextField(verbose_name='Текст комментрия')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата комментария')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created', )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Блогер'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=("user", "author"),
                name="unique_user_author")
        ]

    def __str__(self):
        return f'{self.user} подписан на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {"text": "Текст", "group": "Жанр", 'image': 'Картинка'}
        help_text = {"text": "Введите здесь текст поста",
                     "group": "Выберите жанр",
                     'image': 'Выберите фото'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Текст клмментария'}
        help_text = {'text': 'Введите здесь текст комментария'}

yatube/posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from core.constants.constants import (get_object_or_none,
                                      ELEMENTS_PER_PAGE,
                                      CACHE_SECONDS)
from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


def paginator(request, list):
    paginator = Paginator(list, ELEMENTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(CACHE_SECONDS, key_prefix='index_page')
def index(request):
    post_list = Post.objects.select_related().all()
    page_obj = paginator(request, post_list)
    template = "posts/index.html"
    title = "Последние обновления на сайте"
    title_body = "Последние обновления на сайте"
    context = {
        "page_obj": page_obj,
        "title": title,
        "title_body": title_body,
    }
    return render(request, template, context)


def group_post(request, slug):
    group = get_object_or_404(Group, slug=slug)
    description_body = group.description
    group_list = Post.objects.select_related('group').filter(group=group)
    page_obj = paginator(request, group_list)
    template = "posts/group_list.html"
    title = group.title
    title_body = group.title
    context = {
        "title": title,
        "description_body": description_body,
        "title_body": title_body,
        'slug': slug,
        'page_obj': page_obj,

    }
    return render(request, template, context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = Post.objects.select_related('author').filter(author=user)
    page_obj = paginator(request, posts)
    following = False
    if request.user.is_authenticated:
        is_follow = get_object_or_none(Follow, user=request.user, author=user)
        if is_follow:
            following = True

    if request.user == user:
        not_self_follow = False
    else:
        not_self_follow = True

    context = {
        'username': user,
        'page_obj': page_obj,
        'following': following,
        'not_self_follow': not_self_follow,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    username = post.author
    thirty_symbols = post.text[:30]
    form_comment = CommentForm()
    post_comments = Comment.objects.select_related('post').filter(post=post_id)
    context = {
        'post': post,
        'thirty_symbols': thirty_symbols,
        'post_id': post_id,
        'form_comment': form_comment,
        'post_comments': post_comments,
        'username': username,

    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    if request.method == 'POST':
        form = PostForm(request.POST,
                        files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("posts:profile", post.author)
    form = PostForm()
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    if post.author == request.user:
        if request.method == 'POST':
            form = PostForm(request.POST,
                            files=request.FILES or None,
                            instance=post)
            if form.is_valid():
                form.save()
                return redirect("posts:post_detail", post_id)
        form = PostForm(instance=post)
        return render(request, template, {'form': form, 'is_edit': True,
                                          'post_id': post_id})


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    user = request.user

    posts_list = Post.objects.select_related('author').filter(
        author__following__user=user)
    page_obj = paginator(request, posts_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = User.objects.get(username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author
        )
    return redirect('posts:main')


@login_required
def profile_unfollow(request, username):
    user = request.user
    Follow.objects.get(
        user=User.objects.get(username=user),
        author=User.objects.get(username=username),
    ).delete()
    return redirect('posts:main')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% load user_filters %}
{% block header %}
{% if is_edit %}
<title>Редактирование записи</title>
{% else %}
<title>Новый пост</title>
{% endif %}
{% endblock %}


{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                Редактировать запись
                {% else %}
                Добавить запись
                {% endif %}
              </div>
              <div class="card-body">        

                {% if is_edit %}
                  <form method="post" enctype="multipart/form-data"
                        action="{% url 'posts:post_edit' post_id %}">
                {% else %}
                  <form method="post" enctype="multipart/form-data"
                        action="{% url 'posts:post_create' %}">
                {% endif %}

                  {% csrf_token %}
                  {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      <span class="required text-danger" >*</span>
                    </label>
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help"
                           class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                  </div>
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                      Сохранить
                      {% else %}
                      Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block header %}
<title>Подписки</title>
{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
<main>
    <div class="container py-5">
        <h1>Ваши подписки</h1>
        {% for post in page_obj %}
        {% include 'includes/post_display.html' %}
        {% endfor %}
    </div>
</main>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block header %}
  <title>{{ title }}</title>
{% endblock %}

{% block content %}
<main>
  <div class="container py-5">
    <h1>{{ title_body }}</h1>
    <p>{{ description_body }}</p>

    {% for post in page_obj %}
    {% include 'includes/post_display.html' %}
    {% endfor %}
  </div>
</main>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block header %}
  <title>{{ title }}</title>
{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
<main>
  <div class="container py-5">
    <h1>{{ title_body }}</h1>
    {% for post in page_obj %}
    {% include 'includes/post_display.html' %}
    {% endfor %}
  </div>
</main>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load user_filters %}
{% load thumbnail %}
{% block header %}
    <title>{{ thirty_symbols }}</title>
{% endblock %}

{% block content %}
<main>
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y"}}
                </li>

                {% if post.group %}
                <li class="list-group-item">
                    Группа: {{ post.group.title }}
                    <a href="{% url 'posts:blog' post.group.slug %}">
                        все записи группы
                    </a>
                </li>
                {% endif %}
                <li class="list-group-item">
                    Автор: {{ post.author }}
                </li>
                <li class="list-group-item">
                    Всего постов автора: {{ username.posts.count }}
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.author %}">
                        все посты пользователя
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:post_edit' post_id %}">
                        редактировать запись
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img  class="card-img my-2" src="{{ im.url }}"
            {% endthumbnail %}
            <p>
                {{ post.text }}
            </p>
        </article>
    </div>

    {% if user.is_authenticated %}
    <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}
                <div class="form-group mb-2">
                    {{ form_comment.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        </div>
    </div>
    {% endif %}

    {% for comment in post_comments %}
    <div class="media mb-4">
        <div class="media-body">
            <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                </a>
            </h5>
            <p>
                {{ comment.text }}
            </p>
        </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}

<head>
    {% block header %}
    <title>Профайл пользователя {{ username }}</title>
    {% endblock %}
</head>
{% block content %}
<main>
    <div class="mb-5">
        <h1>Все посты пользователя {{ username }} </h1>
        <h3>Всего постов: {{ username.posts.count }} </h3>
        {% if not_self_follow %}
            {% if following %}
            <a
                    class="btn btn-lg btn-light"
                    href="{% url 'posts:profile_unfollow' username %}" role="button"
            >
                Отписаться
            </a>
            {% else %}
            <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' username %}" role="button"
            >
                Подписаться
            </a>
            {% endif %}
        {% endif %}
    </div>

        {% for post in page_obj %}
        {% include 'includes/post_display.html' %}
        {% endfor %}


    </div>
</main>
{% include 'posts/includes/paginator.html' %}
{% endblock %}
</html>